version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENVIRONMENT: ${ENVIRONMENT}

      DATA_API_URL: ${DATA_API_URL}

      SERVICE_USER_USERNAME: ${SERVICE_USER_USERNAME}
      SERVICE_USER_EMAIL: ${SERVICE_USER_EMAIL}
      SERVICE_USER_PASSWORD: ${SERVICE_USER_PASSWORD}

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_OAUTH_CALLBACK_URL: ${GITHUB_OAUTH_CALLBACK_URL}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      FRONTEND_REDIRECT_URL: ${FRONTEND_REDIRECT_URL}
    container_name: farmhand-api
    depends_on:
      - database
    ports:
      - "8000:8000"
  database:
    image: postgres:17
    container_name: farmhand-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: