sonar.projectKey=farmhand
sonar.projectName=Farmhand API
sonar.projectVersion=0.1

sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/tests/**
sonar.tests=tests

sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=htmlcov/coverage.xml
