spring:
  application:
    name: farmhand
  datasource:
    url: ${APP_DATABASE_URL}
    username: ${APP_DATABASE_USERNAME}
    password: ${APP_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

