"""add size column to field

Revision ID: 17406ea37df3
Revises: 89c7e41e485b
Create Date: 2025-03-18 20:04:30.815795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17406ea37df3'
down_revision: Union[str, None] = '89c7e41e485b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('size', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'size')
    # ### end Alembic commands ###
