"""add index to field table

Revision ID: 314d03b14259
Revises: f5c7a91e8b90
Create Date: 2025-04-13 18:17:44.090182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314d03b14259'
down_revision: Union[str, None] = 'f5c7a91e8b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fields_number'), 'fields', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fields_number'), table_name='fields')
    # ### end Alembic commands ###
