"""create tasks table

Revision ID: 5ce57e1a605f
Revises: d4fe0b3a4c30
Create Date: 2025-06-02 19:40:55.404693

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ce57e1a605f"
down_revision: Union[str, None] = "d4fe0b3a4c30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("content", sa.String(length=280), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("farm_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
