"""Create field & crop models

Revision ID: 72d202149ed3
Revises: d2e50a8c54c6
Create Date: 2025-03-16 02:29:02.835028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d202149ed3'
down_revision: Union[str, None] = 'd2e50a8c54c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ground_type', sa.String(length=50), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('field_type', sa.Enum('BASE_FIELD', 'PRECISION_FARMING_FIELD', name='fieldtypes', native_enum=False), nullable=False),
    sa.Column('plowed', sa.Boolean(), nullable=True),
    sa.Column('rolled', sa.Boolean(), nullable=True),
    sa.Column('weeds', sa.Enum('NO_WEEDS', 'SMALL_WEEDS', 'MEDIUM_WEEDS', 'LARGE_WEEDS', 'SPRAYED_WEEDS', name='weedstates', native_enum=False), nullable=True),
    sa.Column('mulched', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fertilized', sa.Enum('ZER0_PERCENT', 'FIFTY_PERCENT', 'ONE_HUNDRED_PERCENT', name='fertilizerstates', native_enum=False), nullable=False),
    sa.Column('limed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('planted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precision_farming_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nitrogen_level', sa.Integer(), nullable=True),
    sa.Column('ph_level', sa.Double(), nullable=True),
    sa.Column('soil_type', sa.Enum('SANDY_LOAM', 'LOAMY_SAND', 'SILTY_CLAY', 'LOAM', name='soiltypes', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precision_farming_fields')
    op.drop_table('field_crops')
    op.drop_table('base_fields')
    op.drop_table('fields')
    op.drop_table('crops')
    # ### end Alembic commands ###
