"""Create Crops and Field Crops table

Revision ID: 89c7e41e485b
Revises: 4cd61e0650b8
Create Date: 2025-03-17 19:44:39.685141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c7e41e485b'
down_revision: Union[str, None] = '4cd61e0650b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('yield_per_ha', sa.Integer(), nullable=False),
    sa.Column('seeds_per_ha', sa.Integer(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('growth_stages', sa.Integer(), nullable=False),
    sa.Column('growth_duration', sa.Integer(), nullable=False),
    sa.Column('root_crop', sa.Boolean(), nullable=False),
    sa.Column('planted_in', sa.String(length=255), nullable=False),
    sa.Column('harvested_in', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('field_crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('planted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
