"""Create Farm Type and Field Tables

Revision ID: 9b7d1a55eae7
Revises: 5c1d6139bf0e
Create Date: 2025-03-20 23:29:59.266127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7d1a55eae7'
down_revision: Union[str, None] = '5c1d6139bf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('size', sa.Double(), nullable=True),
    sa.Column('ground_type', sa.String(length=50), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('field_type', sa.Enum('PRECISION_FARMING_FIELD', 'BASE_FIELD', name='fieldtypes', native_enum=False), nullable=False),
    sa.Column('plowed', sa.Boolean(), nullable=True),
    sa.Column('rolled', sa.Boolean(), nullable=True),
    sa.Column('weeds', sa.Enum('NO_WEEDS', 'SMALL_WEEDS', 'MEDIUM_WEEDS', 'LARGE_WEEDS', 'SPRAYED_WEEDS', name='weedstates', native_enum=False), nullable=True),
    sa.Column('mulched', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_game_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fertilized', sa.Enum('ZER0_PERCENT', 'FIFTY_PERCENT', 'ONE_HUNDRED_PERCENT', name='fertilizerstates', native_enum=False), nullable=False),
    sa.Column('limed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precision_farming_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nitrogen_level', sa.Integer(), nullable=True),
    sa.Column('ph_level', sa.Double(), nullable=True),
    sa.Column('soil_type', sa.Enum('SANDY_LOAM', 'LOAMY_SAND', 'SILTY_CLAY', 'LOAM', name='soiltypes', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('farms', sa.Column('farm_type', sa.Enum('BASE', 'PRECISION_FARMING', name='farmtypes', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'farm_type')
    op.drop_table('precision_farming_fields')
    op.drop_table('base_game_fields')
    op.drop_table('fields')
    # ### end Alembic commands ###
