"""Add Farm Type to Farm model

Revision ID: d2e50a8c54c6
Revises: 5c1d6139bf0e
Create Date: 2025-03-15 23:30:59.404504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd2e50a8c54c6'
down_revision: Union[str, None] = '5c1d6139bf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('farm_type', sa.Enum('BASE', 'PRECISION_FARMING', name='farmtypes', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'farm_type')
    # ### end Alembic commands ###
