"""initial migration

Revision ID: d4fe0b3a4c30
Revises:
Create Date: 2025-05-31 19:20:22.190729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4fe0b3a4c30"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crops",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("yield_per_ha", sa.Integer(), nullable=False),
        sa.Column("seeds_per_ha", sa.Integer(), nullable=False),
        sa.Column("nitrogen_per_kg_ha", sa.Integer(), nullable=True),
        sa.Column("price", sa.Double(), nullable=False),
        sa.Column("growth_stages", sa.Integer(), nullable=False),
        sa.Column("growth_duration", sa.Integer(), nullable=False),
        sa.Column("root_crop", sa.Boolean(), nullable=False),
        sa.Column("planted_in", sa.String(length=255), nullable=False),
        sa.Column("harvested_in", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )
    op.create_table(
        "maps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("release_date", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("github_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email_address", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_address"),
        sa.UniqueConstraint("github_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "farms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("map_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=True),
        sa.Column(
            "farm_type",
            sa.Enum("BASE", "PRECISION_FARMING", name="farmtypes", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficulty", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["map_id"],
            ["maps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("size", sa.Double(), nullable=True),
        sa.Column("ground_type", sa.String(length=50), nullable=True),
        sa.Column("owned", sa.Boolean(), nullable=False),
        sa.Column("farm_id", sa.UUID(), nullable=False),
        sa.Column(
            "field_type",
            sa.Enum("PRECISION_FARMING_FIELD", "BASE_FIELD", name="fieldtypes", native_enum=False),
            nullable=False,
        ),
        sa.Column("plowed", sa.Boolean(), nullable=True),
        sa.Column("rolled", sa.Boolean(), nullable=True),
        sa.Column("mulched", sa.Boolean(), nullable=True),
        sa.Column(
            "weeds",
            sa.Enum(
                "NO_WEEDS",
                "SMALL_WEEDS",
                "MEDIUM_WEEDS",
                "LARGE_WEEDS",
                "SPRAYED_WEEDS",
                name="weedstates",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fields_number"), "fields", ["number"], unique=False)
    op.create_table(
        "base_game_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fertilized",
            sa.Enum(
                "ZER0_PERCENT",
                "FIFTY_PERCENT",
                "ONE_HUNDRED_PERCENT",
                name="fertilizerstates",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("limed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["fields.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field_crops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("crop_id", sa.Integer(), nullable=False),
        sa.Column("planted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crop_id"],
            ["crops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "precision_farming_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nitrogen_level", sa.Integer(), nullable=True),
        sa.Column("ph_level", sa.Double(), nullable=True),
        sa.Column(
            "soil_type",
            sa.Enum(
                "SANDY_LOAM",
                "LOAMY_SAND",
                "SILTY_CLAY",
                "LOAM",
                name="soiltypes",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["fields.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("precision_farming_fields")
    op.drop_table("field_crops")
    op.drop_table("base_game_fields")
    op.drop_index(op.f("ix_fields_number"), table_name="fields")
    op.drop_table("fields")
    op.drop_table("farms")
    op.drop_table("users")
    op.drop_table("maps")
    op.drop_table("crops")
    # ### end Alembic commands ###
