"""Add nitrogen_level to crops table

Revision ID: f5c7a91e8b90
Revises: e45ffa307ff0
Create Date: 2025-04-05 20:32:14.264797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c7a91e8b90'
down_revision: Union[str, None] = 'e45ffa307ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops', sa.Column('nitrogen_per_kg_ha', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crops', 'nitrogen_per_kg_ha')
    # ### end Alembic commands ###
